### ISSUE TITLE
Test-Targets need `trigger_high()` Dummy Function

### ISSUE THREAD

**Issue by nils-wisiol** [nils-wisiol/m4sc#23]
For the chipwhisperer, we need to call `trigger_high` to indicate when to start tracing. Hence, for host, qemu, discovery, we need to have stub functions that just do nothing, but let the code compile.

@TeumessianFox please add for discovery
@hnj2 please add for host, qemu

**Comment by TeumessianFox** [comment]
I would say we just add a preprocessor IF condition into the main.c which only adds the trigger_high if the cw is used. I will make a PR as soon as it's done

**Comment by nils-wisiol** [comment]
`trigger_low();`, needs to be supported as well

**Comment by TeumessianFox** [comment]
I will make sure to add Dummy trigger functions to the next PR for everything except the cw

**Comment by nils-wisiol** [comment]
`setup_trigger` dummy function may need to be removed/changed, otherwise please close this @TeumessianFox

**Comment by hnj2** [comment]
Imho this issue is dealt with, right?

**Comment by nils-wisiol** [comment]
ping @TeumessianFox

**Comment by TeumessianFox** [comment]
Ups, yes I think everything should work by now
