### ISSUE TITLE
Building QEMU

### ISSUE THREAD

**Issue by nils-wisiol** [nils-wisiol/m4sc#26]
Currently does not work, or at least does not work according to README, see build failures in #19 when executing `make build-qemu VICTIM_TARGET=qemu VICTIM_NAME=schoolbook32`

**Comment by hnj2** [comment]
The readme says `qemu-build`, which is probably what the problem is here ;)

**Comment by hnj2** [comment]
Yup worked!

**Comment by nils-wisiol** [comment]
oh my 🙈 thanks!
