### ISSUE TITLE
Argument parsing code duplication

### ISSUE THREAD

**Issue by hnj2** [nils-wisiol/m4sc#30]
There seems to be a lot of code duplication in the argument parsing in `m4sc/__main__.py` (and to some extend in `conftest.py`).

Maybe we should create config-objects that can add their options to an arg-parser and can be created from the result of `parser.parse_args(args)`.

**Comment by hnj2** [comment]
@nils-wisiol If you think the outlined approach is a good idea, I'll start on the implementation.

**Comment by nils-wisiol** [comment]
Yes, let's get rid of that eventually. I would assign low priority to this issue though.

**Comment by hnj2** [comment]
hey @TeumessianFox why was this issue closed?

**Comment by TeumessianFox** [comment]
I thought it is all done as the corresponding PR was merged. If I was wrong please just reopen the issue.

**Comment by hnj2** [comment]
I think #29 Is done ... this Issue is still open, but low priority :)

**Comment by nils-wisiol** [comment]
Yeah let's eventually resolve this

**Comment by hnj2** [comment]
Okay I'm on it
